name: Upload userContent.css as asset

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload userContent.css
        uses: softprops/action-gh-release@v1
        with:
          files: src/userContent.css
          token: ${{ secrets.GITHUB_TOKEN }}
